//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System;

public class DamageBundle
{
	public Weapon weapon;
	public Spell spell;
	public GameObject source;
	public RaycastHit hit;

	public DamageBundle (Weapon weapon, GameObject source, RaycastHit hit)
	{
		this.weapon = weapon;
		this.source = source;
		this.hit = hit;
//		Debug.LogWarning("Damage bundle created with weapon "+weapon.name);
	}

	public DamageBundle (Spell spell, GameObject source, RaycastHit hit)
	{
		this.spell = spell;
		this.source = source;
		this.hit = hit;
	}
}

