//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class Buff
{
	
	public float healthRestored=0;
	public float manaRestored = 0;

	public int damageBuff=0;
	public float attackSpeedBuff = 0;
	public int movementSpeedBuff = 0;
	public float armorBuff = 0;
	public int fireResistBuff = 0;
	public int iceResistBuff = 0;
	public int lightningResistBuff = 0;
	public int chaosResistBuff = 0;

	public float duration;
	public float totalDuration;

	public float totalHealthRestored;
	public float totalManaRestored;

	//consider all potions a buff
	public Buff(Potion.PotionPropertyBundle potionPropertyBundle, float duration){
		this.healthRestored=potionPropertyBundle.healthRestored;
		this.manaRestored = potionPropertyBundle.manaRestored;
		this.damageBuff=potionPropertyBundle.damageBuff;
		this.attackSpeedBuff = potionPropertyBundle.attackSpeedBuff;
		this.movementSpeedBuff = potionPropertyBundle.movementSpeedBuff;
		this.armorBuff = potionPropertyBundle.armorBuff;
		this.fireResistBuff = potionPropertyBundle.fireResistBuff;
		this.iceResistBuff = potionPropertyBundle.iceResistBuff;
		this.lightningResistBuff = potionPropertyBundle.lightningResistBuff;
		this.chaosResistBuff = potionPropertyBundle.chaosResistBuff;
		this.duration = duration; //duration is ignored for health/mana potions??

		totalDuration = duration;
		totalHealthRestored = healthRestored;
		totalManaRestored = manaRestored;

	}

}


