//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using AssemblyCSharp;

public static class Global
{
	
	public static EquippedItemIndex equippedItemIndex = GameObject.FindGameObjectWithTag("EquippedItemIndex").GetComponent<EquippedItemIndex>();
	public static CombatSystem combatSystem = GameObject.FindGameObjectWithTag("Player").GetComponent<CombatSystem>();
	public static Inventory inventory = GameObject.FindGameObjectWithTag("Player").GetComponentInChildren<Inventory>();
	public static CharacterPage characterPage = GameObject.FindGameObjectWithTag("Player").GetComponentInChildren<CharacterPage>();
	public static ItemFactory itemFactory = new ItemFactory();
	public static AnimationController arms = GameObject.FindGameObjectWithTag("Arms").GetComponentInChildren<AnimationController> ();
	public static SpellSystem SpellSystem = GameObject.FindGameObjectWithTag("Player").GetComponent<SpellSystem>();
	public static int OpenGUICount=0;
	public static bool IsGUIOpen = false;
	public static GameObject LoadArrow = GameObject.FindGameObjectWithTag("LoadArrow");
		
}

